<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeLeaveManagement.Domain\EmployeeLeaveManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Common\" />
    <Folder Include="Abstractions\Repositories\" />
    <Folder Include="DTOs\Employee\" />
    <Folder Include="DTOs\Department\" />
    <Folder Include="DTOs\LeaveRequest\" />
    <Folder Include="DTOs\LeaveType\" />
    <Folder Include="Mappings\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>
